/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import service.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kesya
 */

public class FormDataPelanggan extends javax.swing.JInternalFrame{
    public FormDataPelanggan() {
        initComponents();
        tampilData();
        tampilDataDenganHeaderCustom();
        
        txtCariData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariDataCaretUpdate(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoIdentitas = new javax.swing.JTextField();
        txtNamaplg = new javax.swing.JTextField();
        txtNoHPplg = new javax.swing.JTextField();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLakiLaki = new javax.swing.JRadioButton();
        rbKtp = new javax.swing.JRadioButton();
        rbSim = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnCariData = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatplg = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtTgldaftar = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(685, 600));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(685, 600));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(685, 320));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("No. Identitas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("No.HP");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal");

        txtNoIdentitas.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNoIdentitasCaretUpdate(evt);
            }
        });
        txtNoIdentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoIdentitasActionPerformed(evt);
            }
        });

        txtNamaplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaplgActionPerformed(evt);
            }
        });

        txtNoHPplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHPplgActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbLakiLaki);
        rbLakiLaki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbLakiLaki.setText("Laki-Laki");
        rbLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKtp);
        rbKtp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbKtp.setText("KTP");
        rbKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKtpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSim);
        rbSim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbSim.setText("SIM");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnCariData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCariData.setText("Cari Data");
        btnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataActionPerformed(evt);
            }
        });

        txtCariData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariDataCaretUpdate(evt);
            }
        });
        txtCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariDataActionPerformed(evt);
            }
        });

        txtAlamatplg.setColumns(20);
        txtAlamatplg.setRows(5);
        jScrollPane1.setViewportView(txtAlamatplg);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNoIdentitas)
                                .addGap(18, 18, 18)
                                .addComponent(rbKtp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSim))
                            .addComponent(txtNamaplg)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbPerempuan)
                                .addGap(18, 18, 18)
                                .addComponent(rbLakiLaki))
                            .addComponent(txtNoHPplg)
                            .addComponent(txtTgldaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCariData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnCariData, btnClose, btnDelete, btnEdit, btnSave});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCariData)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbKtp)
                            .addComponent(rbSim)
                            .addComponent(btnAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamaplg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(15, 15, 15)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbPerempuan)
                            .addComponent(rbLakiLaki))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNoHPplg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTgldaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        tblPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Identitas", "Jenis Identitas", "Nama", "Alamat", "Jenis Kelamin", "No. HP", "Tanggal"
            }
        ));
        jScrollPane2.setViewportView(tblPelanggan);
        tblPelanggan.getAccessibleContext().setAccessibleParent(jScrollPane1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM ENTRI DATA PELANGGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tampilData() {
        try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql="SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal FROM tblpelanggan";
                ResultSet r=s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}
    
    public void tampilDataDenganHeaderCustom() {
    try {
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal FROM tblpelanggan";
        ResultSet r = s.executeQuery(sql);

        // Pakai DbUtils untuk isi datanya
        tblPelanggan.setModel(DbUtils.resultSetToTableModel(r));

        // Ganti nama header langsung
        String[] namaKolom = {
            "No. Identitas",
            "Jenis Identitas",
            "Nama",
            "Alamat",
            "Jenis Kelamin",
            "No. HP",
            "Tanggal"
        };

        for (int i = 0; i < namaKolom.length; i++) {
            tblPelanggan.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
        }

        tblPelanggan.getTableHeader().repaint();
        r.close();
        s.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    private void txtNoIdentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoIdentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoIdentitasActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void rbKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKtpActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        txtNoIdentitas.setText("");
        txtNamaplg.setText("");
        txtAlamatplg.setText("");
        txtNoHPplg.setText("");
        txtCariData.setText("");
        buttonGroup1.clearSelection(); // KTP/SIM
        buttonGroup2.clearSelection();
        txtTgldaftar.setDate(null);
        txtNoIdentitas.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// SAVE
java.util.Date Tanggal = this.txtTgldaftar.getDate();
String NoIdentitas = this.txtNoIdentitas.getText();
String Nama = this.txtNamaplg.getText();
String Alamat = this.txtAlamatplg.getText();
String NoHP = this.txtNoHPplg.getText();

String JenisIdentitas = null;
if(rbKtp.isSelected()){
    JenisIdentitas = "KTP";
} else if (rbSim.isSelected()){
    JenisIdentitas = "SIM";
}

String JenisKelamin  = null;
if(rbLakiLaki.isSelected()){
    JenisKelamin  = "Laki-Laki";
} else if (rbPerempuan.isSelected()){
    JenisKelamin  = "Perempuan";
}

// Validasi satu-satu
if(txtNoIdentitas.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Identitas Tidak Boleh Kosong");
} else {
    if (txtNamaplg.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Pelanggan Tidak Boleh Kosong");
    } else {
        if (txtAlamatplg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
        } else {
            if (txtNoHPplg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor HP Tidak Boleh Kosong");
            } else {
                if (JenisIdentitas == null) {
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Jenis Identitas Harus Dipilih");
                } else {
                    if (JenisKelamin == null) {
                        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Jenis Kelamin Harus Dipilih");
                    } else {
                        if (Tanggal == null) {
                            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Tanggal Harus Diisi");
                        } else {
                            try {
                                Connection c = ClassDatabase.getKoneksi();
                                String sql = "INSERT INTO tblpelanggan (NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal) VALUES (?, ?, ?, ?, ?, ?, ?)";
                                PreparedStatement p = c.prepareStatement(sql);
                                p.setString(1, NoIdentitas);
                                p.setString(2, JenisIdentitas);
                                p.setString(3, Nama);
                                p.setString(4, Alamat);
                                p.setString(5, JenisKelamin);
                                p.setString(6, NoHP);
                                p.setDate(7, new java.sql.Date(Tanggal.getTime()));
                                p.executeUpdate();
                                p.close();
                                JOptionPane.showMessageDialog(this, "Sukses Tambah Data");
                            } catch(SQLException e){
                                System.out.println("Kesalahan SQL: " + e);
                            }

                            // Refresh tabel setelah insert
                            try {
                                Connection c = ClassDatabase.getKoneksi();
                                Statement s = c.createStatement();
                                String sql = "SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal FROM tblpelanggan";
                                ResultSet r = s.executeQuery(sql);
                                tampilDataDenganHeaderCustom();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, e);
                            }
                        }
                    }
                }
            }
        }
    }
}

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//Delete
        java.util.Date Tanggal=(java.util.Date) this.txtTgldaftar.getDate();
            String NoIdentitas=this.txtNoIdentitas.getText();
            try {
                Connection c = ClassDatabase.getKoneksi();
                String sql = "DELETE FROM tblpelanggan WHERE NoIdentitas = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, NoIdentitas);
                
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Sukses Hapus Data");   
            }catch(SQLException e) {
                System.out.println(e);
            }finally{
            }
            try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal FROM tblpelanggan";
                ResultSet r = s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rbLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiLakiActionPerformed

    private void txtNamaplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaplgActionPerformed

    private void txtNoHPplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHPplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHPplgActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataActionPerformed
//Cari Data
    try {            
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM tblpelanggan WHERE NoIdentitas='" + txtCariData.getText() + "'";
        ResultSet r = s.executeQuery(sql);
        
        while (r.next()) {
            txtNoIdentitas.setText(r.getString("NoIdentitas"));
            txtNamaplg.setText(r.getString("Nama"));
            txtAlamatplg.setText(r.getString("Alamat"));
            txtTgldaftar.setDate(r.getDate("Tanggal"));
            txtNoHPplg.setText(r.getString("NoHP")); 

            if ("KTP".equalsIgnoreCase(r.getString("JenisIdentitas"))) {
                rbKtp.setSelected(true);
            } else {
                rbSim.setSelected(true);
            }

            if ("Laki-Laki".equalsIgnoreCase(r.getString("JenisKelamin"))) {
                rbLakiLaki.setSelected(true);
            } else {
                rbPerempuan.setSelected(true);
            }
        }

        r.close();
        s.close();
    } catch (SQLException e) {
        System.out.println("Terjadi kesalahan: " + e);
    }
    }//GEN-LAST:event_btnCariDataActionPerformed

    private void txtCariDataCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCariDataCaretUpdate
        // TODO add your handling code here:
        String keyword = txtCariData.getText();
        try {
            Connection c = ClassDatabase.getKoneksi();
            String sql = "SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal " +
                         "FROM tblpelanggan " +
                         "WHERE NoIdentitas     LIKE ? " +
                         "   OR JenisIdentitas  LIKE ? " +
                         "   OR Nama            LIKE ? " +
                         "   OR Alamat          LIKE ? " +
                         "   OR JenisKelamin    LIKE ? " +
                         "   OR NoHP            LIKE ? " +
                         "   OR Tanggal         LIKE ? ";
            PreparedStatement p = c.prepareStatement(sql);
            String key = "%" + keyword + "%";
                for (int i = 1; i <= 7; i++) {
                    p.setString(i, key);
                }
            ResultSet r = p.executeQuery();
            tampilDataDenganHeaderCustom();
            r.close();
            p.close();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtCariDataCaretUpdate

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
//Update
        java.util.Date Tanggal=(java.util.Date) this.txtTgldaftar.getDate();
            String NoIdentitas =this.txtNoIdentitas.getText();
            String Nama =this.txtNamaplg.getText();
            String JenisIdentitas = null;
            if(rbKtp.isSelected()){
                JenisIdentitas = "KTP";
            } else if (rbSim.isSelected()){
                JenisIdentitas = "SIM";
            }
            String JenisKelamin = null;
            if(rbLakiLaki.isSelected()){
                JenisKelamin = "Laki-Laki";
            } else if (rbPerempuan.isSelected()){
                JenisKelamin = "Perempuan";
            }
            String Alamat = this.txtAlamatplg.getText();
            String NoHP = this.txtNoHPplg.getText();
                 if(txtNoIdentitas.getText().isEmpty())
            {
              JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Identitas Pelanggan Tidak Boleh Kosong");
            } 
            else{
                if (txtNamaplg.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Pelanggan Tidak Boleh Kosong");
                }
                else{
                    if (txtAlamatplg.getText().isEmpty())
                    {
                        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
                    }
                    else{
                        if (txtNoHPplg.getText().isEmpty())
                        {
                            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor HP Tidak Boleh Kosong");

                        }
                        else{
                            try{
                                    Connection c = ClassDatabase.getKoneksi();
                                    String sql = "UPDATE tblpelanggan SET JenisIdentitas = ?, Nama = ?, Alamat = ?, JenisKelamin = ?, NoHP = ?, Tanggal = ? WHERE NoIdentitas = ?";
                                    PreparedStatement p = c.prepareStatement(sql);
                                    p.setString(1, JenisIdentitas);
                                    p.setString(2, Nama);
                                    p.setString(3, Alamat);
                                    p.setString(4, JenisKelamin);
                                    p.setString(5, NoHP);
                                    p.setDate(6, new java.sql.Date(Tanggal.getTime()));
                                    p.setString(7, NoIdentitas);
                                    p.executeUpdate();
                                    p.close();
                                    JOptionPane.showMessageDialog(this, "Sukses Update Data");       
                                        }catch(SQLException e){
                                            System.out.println(e);
                                        }finally{
                                      }}}}} try {
                                               Connection c = ClassDatabase.getKoneksi();
                                                Statement s = c.createStatement();
                                                String sql = "SELECT NoIdentitas, JenisIdentitas, Nama, Alamat, JenisKelamin, NoHP, Tanggal FROM tblpelanggan";
                                                ResultSet r = s.executeQuery(sql);
                                                tampilDataDenganHeaderCustom();
                                       }catch (Exception e){
                                           JOptionPane.showMessageDialog(null, e);
                                       }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNoIdentitasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoIdentitasCaretUpdate
        try {            
            Connection c = ClassDatabase.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tblpelanggan WHERE NoIdentitas='" + this.txtNoIdentitas.getText() + "'";
            ResultSet r=s.executeQuery(sql);
           while (r.next()){
                this.txtNamaplg.setText(r.getString(3));
                if ("KTP".equalsIgnoreCase(r.getString("JenisIdentitas"))){
                    rbKtp.setSelected(true);
                } else {
                    rbSim.setSelected(true);
                }  
                if ("Laki-Laki".equalsIgnoreCase(r.getString("JenisKelamin"))){
                    rbLakiLaki.setSelected(true);
                } else {
                    rbPerempuan.setSelected(true);
                }                 
                this.txtAlamatplg.setText(r.getString("Alamat"));
                this.txtTgldaftar.setDate(r.getDate("Tanggal"));
                this.txtNoHPplg.setText(r.getString("NoHP")); 
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
    }//GEN-LAST:event_txtNoIdentitasCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbKtp;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextArea txtAlamatplg;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtNamaplg;
    private javax.swing.JTextField txtNoHPplg;
    private javax.swing.JTextField txtNoIdentitas;
    private com.toedter.calendar.JDateChooser txtTgldaftar;
    // End of variables declaration//GEN-END:variables
}