/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import service.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Kesya
 */
public class FormDataPembelianSparepart extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataPembelianSparepart
     */
    public FormDataPembelianSparepart() {
        initComponents();
        tampilData();
        tampilDataDenganHeaderCustom();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMerah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BgPink = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoPembelian = new javax.swing.JTextField();
        txtKodeSp = new javax.swing.JTextField();
        txtNamaSp = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtTotalStok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtJumlahBeli = new javax.swing.JTextField();
        tglPembelian = new com.toedter.calendar.JDateChooser();
        txtKodeSup = new javax.swing.JTextField();
        txtNamaSup = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTampilkan = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();

        PanelMerah.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM ENTRI DATA PEMBELIAN SPAREPART");
        jLabel1.setMaximumSize(new java.awt.Dimension(327, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(327, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(327, 32));

        BgPink.setBackground(new java.awt.Color(255, 204, 204));
        BgPink.setPreferredSize(new java.awt.Dimension(655, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kesa Sparepart");

        javax.swing.GroupLayout BgPinkLayout = new javax.swing.GroupLayout(BgPink);
        BgPink.setLayout(BgPinkLayout);
        BgPinkLayout.setHorizontalGroup(
            BgPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgPinkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        BgPinkLayout.setVerticalGroup(
            BgPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgPinkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nama Sparepart");
        jLabel3.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("No. Pembelian");
        jLabel4.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Kode Sparepart");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Harga Beli");
        jLabel7.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Harga Jual");
        jLabel8.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Total Stok");
        jLabel10.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(132, 25));

        txtNoPembelian.setScrollOffset(3);
        txtNoPembelian.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNoPembelianCaretUpdate(evt);
            }
        });
        txtNoPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPembelianActionPerformed(evt);
            }
        });

        txtKodeSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeSpActionPerformed(evt);
            }
        });
        txtKodeSp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeSpKeyReleased(evt);
            }
        });

        txtNamaSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSpActionPerformed(evt);
            }
        });

        txtHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBeliActionPerformed(evt);
            }
        });

        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });

        txtTotalStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalStokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtTotalStok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaSp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKodeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoPembelian)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodeSp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Jumlah Beli");
        jLabel9.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Tanggal Pembelian");
        jLabel11.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Kode Supplier");
        jLabel12.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Nama Supplier");
        jLabel13.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(132, 25));

        txtJumlahBeli.setScrollOffset(3);

        txtKodeSup.setScrollOffset(3);
        txtKodeSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeSupKeyReleased(evt);
            }
        });

        txtNamaSup.setScrollOffset(3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtKodeSup)
                    .addComponent(tglPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtJumlahBeli)
                    .addComponent(txtNamaSup))
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaSup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        btnTampilkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        txtCariData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariDataCaretUpdate(evt);
            }
        });
        txtCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampilkan)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setLabel("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPembelian);

        javax.swing.GroupLayout PanelMerahLayout = new javax.swing.GroupLayout(PanelMerah);
        PanelMerah.setLayout(PanelMerahLayout);
        PanelMerahLayout.setHorizontalGroup(
            PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(BgPink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(PanelMerahLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMerahLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PanelMerahLayout.setVerticalGroup(
            PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMerahLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BgPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMerahLayout.createSequentialGroup()
                        .addGroup(PanelMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void tampilData() {
        try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT NoPembelian, KodeSp, JumlahBeli, TanggalPembelian, KodeSup FROM tbldatapembelian";
                ResultSet r = s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}
    
    public void tampilDataDenganHeaderCustom() {
    try {
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT NoPembelian, KodeSp, JumlahBeli, TanggalPembelian, KodeSup FROM tbldatapembelian";
        ResultSet r = s.executeQuery(sql);

        // Pakai DbUtils untuk isi datanya
        tblPembelian.setModel(DbUtils.resultSetToTableModel(r));

        // Ganti nama header langsung
        String[] namaKolom = {
            "No Pembelian",
            "Kode Sparepart",
            "Jumlah Beli",
            "Tanggal Pembelian",
            "Kode Supplier"
        };

        for (int i = 0; i < namaKolom.length; i++) {
            tblPembelian.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
        }

        tblPembelian.getTableHeader().repaint();
        r.close();
        s.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    
public void tampilDataSparepart() {
    System.out.println("DEBUG KodeSp dari form: " + txtKodeSp.getText()); // TARUH INI

    try {
        Connection c = ClassDatabase.getKoneksi();
        String sql = "SELECT * FROM tbldatabarang WHERE KodeSp = ?";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, txtKodeSp.getText());
        ResultSet r = p.executeQuery();

        if (r.next()) {
            txtNamaSp.setText(r.getString("NamaSp"));
            txtHargaBeli.setText(r.getString("HargaBeli"));
            txtHargaJual.setText(r.getString("HargaJual"));
            txtTotalStok.setText(r.getString("Stok"));
        } else {
            txtNamaSp.setText("");
            txtHargaBeli.setText("");
            txtHargaJual.setText("");
            txtTotalStok.setText("");
        }

        r.close();
        p.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil data sparepart: " + e.getMessage());
    }
}

public void tampilDataSupplier() {
    System.out.println("DEBUG KodeSup dari form: " + txtKodeSup.getText()); // TARUH INI

    try {
        Connection c = ClassDatabase.getKoneksi();
        String sql = "SELECT * FROM tbldatasup WHERE KodeSup = ?";
        PreparedStatement p = c.prepareStatement(sql);
        
        if (!txtKodeSup.getText().isEmpty()) {
            p.setInt(1, Integer.parseInt(txtKodeSup.getText())); // INT bukan String!
        } else {
            return;
        }

        ResultSet r = p.executeQuery();

        if (r.next()) {
            txtNamaSup.setText(r.getString("NamaSup"));
        } else {
            txtNamaSup.setText("");
        }

        r.close();
        p.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil data supplier: " + e.getMessage());
    }
}
    private void txtNoPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPembelianActionPerformed

    private void txtKodeSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeSpActionPerformed

    private void txtNamaSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSpActionPerformed

    private void txtHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBeliActionPerformed

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void txtTotalStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalStokActionPerformed

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
//Cari Data 
    try {
        Connection c = ClassDatabase.getKoneksi();
        String noPembelian = txtCariData.getText().trim(); // atau txtNoPembelian
        String sql = "SELECT * FROM tbldatapembelian WHERE NoPembelian = ?";
        PreparedStatement ps = c.prepareStatement(sql);
        ps.setString(1, noPembelian);
        ResultSet r = ps.executeQuery();

        if (r.next()) {
            txtNoPembelian.setText(r.getString("NoPembelian"));
            txtKodeSp.setText(r.getString("KodeSp"));
            txtJumlahBeli.setText(r.getString("JumlahBeli"));
            tglPembelian.setDate(r.getDate("TanggalPembelian"));
            txtKodeSup.setText(r.getString("KodeSup"));

            // Auto isi nama barang dan supplier
            tampilDataSparepart();
            tampilDataSupplier();
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan.");
        }

        r.close();
        ps.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void txtCariDataCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCariDataCaretUpdate
try {
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String keyword = txtCariData.getText().trim();
        String sql = "SELECT NoPembelian, KodeSp, JumlahBeli, TanggalPembelian, KodeSup " +
                     "FROM tbldatapembelian " +
                     "WHERE NoPembelian LIKE '%" + keyword + "%' OR " +
                     "KodeSp LIKE '%" + keyword + "%' OR " +
                     "JumlahBeli LIKE '%" + keyword + "%' OR " +
                     "TanggalPembelian LIKE '%" + keyword + "%' OR " +
                     "KodeSup LIKE '%" + keyword + "%'";

        ResultSet r = s.executeQuery(sql);
        tblPembelian.setModel(DbUtils.resultSetToTableModel(r));

        // Atur ulang header kolomnya agar tetap rapi
        String[] namaKolom = {
            "No Pembelian",
            "Kode Sparepart",
            "Jumlah Beli",
            "Tanggal Pembelian",
            "Kode Supplier"
        };
        for (int i = 0; i < namaKolom.length; i++) {
            tblPembelian.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
        }
        tblPembelian.getTableHeader().repaint();

        r.close();
        s.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data: " + e.getMessage());
    }
    }//GEN-LAST:event_txtCariDataCaretUpdate

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtNoPembelian.setText("");
        txtKodeSp.setText("");
        txtJumlahBeli.setText("");
        txtCariData.setText("");
        tglPembelian.setDate(null);
        txtKodeSup.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// SAVE
java.util.Date TanggalPembelian = this.tglPembelian.getDate();
String NoPembelian = this.txtNoPembelian.getText();
String KodeSp = this.txtKodeSp.getText();
String JumlahBeli = this.txtJumlahBeli.getText();
String KodeSup = this.txtKodeSup.getText();

try {
    Connection c = ClassDatabase.getKoneksi();

    // Cek apakah NoPembelian sudah ada
    String cekSql = "SELECT * FROM tbldatapembelian WHERE NoPembelian = ?";
    PreparedStatement cekStmt = c.prepareStatement(cekSql);
    cekStmt.setString(1, NoPembelian);
    ResultSet rs = cekStmt.executeQuery();

    if (rs.next()) {
        // Sudah ada di database
        JOptionPane.showMessageDialog(this, "No Pembelian sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        // Belum ada, lanjutkan INSERT
        String sql = "INSERT INTO tbldatapembelian (NoPembelian, KodeSp, JumlahBeli, TanggalPembelian, KodeSup) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, NoPembelian);
        p.setString(2, KodeSp);
        p.setString(3, JumlahBeli);
        p.setDate(4, new java.sql.Date(TanggalPembelian.getTime()));
        p.setString(5, KodeSup);
        p.executeUpdate();
        p.close();

        JOptionPane.showMessageDialog(this, "Sukses Tambah Data");

        // Refresh tabel setelah insert
        try {
            Statement s = c.createStatement();
            String sqlRefresh = "SELECT NoPembelian, KodeSp, JumlahBeli, TanggalPembelian, KodeSup FROM tbldatapembelian";
            ResultSet r = s.executeQuery(sqlRefresh);
            tampilDataDenganHeaderCustom();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    cekStmt.close();
    rs.close();

} catch (SQLException e) {
    System.out.println("Kesalahan SQL: " + e);
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNoPembelianCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoPembelianCaretUpdate
return;
    }//GEN-LAST:event_txtNoPembelianCaretUpdate

    private void txtKodeSpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeSpKeyReleased
tampilDataSparepart();
    }//GEN-LAST:event_txtKodeSpKeyReleased

    private void txtKodeSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeSupKeyReleased
tampilDataSupplier();
    }//GEN-LAST:event_txtKodeSupKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPink;
    private javax.swing.JPanel PanelMerah;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPembelian;
    private com.toedter.calendar.JDateChooser tglPembelian;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtJumlahBeli;
    private javax.swing.JTextField txtKodeSp;
    private javax.swing.JTextField txtKodeSup;
    private javax.swing.JTextField txtNamaSp;
    private javax.swing.JTextField txtNamaSup;
    private javax.swing.JTextField txtNoPembelian;
    private javax.swing.JTextField txtTotalStok;
    // End of variables declaration//GEN-END:variables
}
