/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import service.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kesya
 */
public class FormDataPenjualanSparepart extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataPenjualanSparepart
     */
    public FormDataPenjualanSparepart() {
        initComponents();
        tampilData();
        tampilDataDenganHeaderCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgMerah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNoPenjualan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKodeSp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNamaSp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtQty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tglPenjualan = new com.toedter.calendar.JDateChooser();
        btnDiskon = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnTampilkan = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();

        BgMerah.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM ENTRI DATA PENJUALAN SPAREPART");
        jLabel1.setMaximumSize(new java.awt.Dimension(327, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(327, 32));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(655, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kesa Sparepart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("No. Penjualan");
        jLabel3.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Kode Sparepart");

        txtKodeSp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeSpKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nama Sparepart");
        jLabel5.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Harga");
        jLabel6.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Stok");
        jLabel7.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(132, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStok, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeSp)
                    .addComponent(txtNamaSp))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKodeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaSp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(355, 159));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Qty");
        jLabel8.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(132, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tanggal");
        jLabel9.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(132, 25));

        txtDiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiskonKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Total");
        jLabel11.setMaximumSize(new java.awt.Dimension(132, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(132, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(132, 25));

        btnDiskon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDiskon.setText("Diskon?");
        btnDiskon.setMaximumSize(new java.awt.Dimension(72, 27));
        btnDiskon.setMinimumSize(new java.awt.Dimension(72, 27));
        btnDiskon.setPreferredSize(new java.awt.Dimension(72, 27));
        btnDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiskonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQty, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglPenjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtTotal))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(85, 139));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnClose, btnSave});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        btnTampilkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.setMaximumSize(new java.awt.Dimension(72, 27));
        btnTampilkan.setMinimumSize(new java.awt.Dimension(72, 27));
        btnTampilkan.setPreferredSize(new java.awt.Dimension(72, 27));
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        txtCariData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCariDataCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        javax.swing.GroupLayout BgMerahLayout = new javax.swing.GroupLayout(BgMerah);
        BgMerah.setLayout(BgMerahLayout);
        BgMerahLayout.setHorizontalGroup(
            BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BgMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(BgMerahLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BgMerahLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        BgMerahLayout.setVerticalGroup(
            BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgMerahLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BgMerahLayout.createSequentialGroup()
                        .addGroup(BgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void tampilData() {
        try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT NoPenjualan, KodeSp, Qty, Tanggal, Diskon, Total FROM tbldatapenjualan";
                ResultSet r = s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}
    
    public void tampilDataDenganHeaderCustom() {
    try {
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT NoPenjualan, KodeSp, Qty, Tanggal, Diskon, Total FROM tbldatapenjualan";
        ResultSet r = s.executeQuery(sql);

        // Pakai DbUtils untuk isi datanya
        tblPenjualan.setModel(DbUtils.resultSetToTableModel(r));

        // Ganti nama header langsung
        String[] namaKolom = {
            "No Penjualan",
            "Kode Sparepart",
            "Qty",
            "Tanggal",
            "Diskon",
            "Total"
        };

        for (int i = 0; i < namaKolom.length; i++) {
            tblPenjualan.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
        }

        tblPenjualan.getTableHeader().repaint();
        r.close();
        s.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    
public void tampilDataSparepart() {
    System.out.println("DEBUG KodeSp dari form: " + txtKodeSp.getText()); // TARUH INI

    try {
        Connection c = ClassDatabase.getKoneksi();
        String sql = "SELECT * FROM tbldatabarang WHERE KodeSp = ?";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, txtKodeSp.getText());
        ResultSet r = p.executeQuery();

        if (r.next()) {
            txtNamaSp.setText(r.getString("NamaSp"));
            txtHarga.setText(r.getString("HargaJual"));
            txtStok.setText(r.getString("Stok"));
        } else {
            txtNamaSp.setText("");
            txtHarga.setText("");
            txtStok.setText("");
        }

        r.close();
        p.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil data sparepart: " + e.getMessage());
    }
}

private void hitungTotal() {
    try {
        int harga = Integer.parseInt(txtHarga.getText().trim());
        int qty = Integer.parseInt(txtQty.getText().trim());
        int diskon = 0;

        if (!txtDiskon.getText().trim().isEmpty()) {
            diskon = Integer.parseInt(txtDiskon.getText().trim());
        }

        int total = (harga * qty) - diskon;
        txtTotal.setText(String.valueOf(total));

    } catch (NumberFormatException e) {
        // Boleh kosongin atau kasih warning kalau mau
        txtTotal.setText("0");
    }
}
    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
//Cari Data 
    try {
        Connection c = ClassDatabase.getKoneksi();
        String noPenjualan = txtCariData.getText().trim(); // atau txtNoPembelian
        String sql = "SELECT * FROM tbldatapenjualan WHERE NoPenjualan = ?";
        PreparedStatement ps = c.prepareStatement(sql);
        ps.setString(1, noPenjualan);
        ResultSet r = ps.executeQuery();

        if (r.next()) {
            txtNoPenjualan.setText(r.getString("NoPenjualan"));
            txtKodeSp.setText(r.getString("KodeSp"));
            txtQty.setText(r.getString("Qty"));
            tglPenjualan.setDate(r.getDate("Tanggal"));
            txtTotal.setText(r.getString("Total"));

            // Auto isi nama barang dan supplier
            tampilDataSparepart();
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan.");
        }

        r.close();
        ps.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// SAVE PENJUALAN
java.util.Date Tanggal = this.tglPenjualan.getDate(); // Pastikan ini field-nya
String NoPenjualan = this.txtNoPenjualan.getText();
String KodeSp = this.txtKodeSp.getText();
String Qty = this.txtQty.getText();
String Diskon = this.txtDiskon.getText();
String Total = this.txtTotal.getText();

try {
    Connection c = ClassDatabase.getKoneksi();

    // Cek apakah NoPenjualan sudah ada
    String cekSql = "SELECT * FROM tbldatapenjualan WHERE NoPenjualan = ?";
    PreparedStatement cekStmt = c.prepareStatement(cekSql);
    cekStmt.setString(1, NoPenjualan);
    ResultSet rs = cekStmt.executeQuery();

    if (rs.next()) {
        JOptionPane.showMessageDialog(this, "No Penjualan sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        // Insert data baru
        String sql = "INSERT INTO tbldatapenjualan (NoPenjualan, KodeSp, Qty, Tanggal, Diskon, Total) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, NoPenjualan);
        p.setString(2, KodeSp);
        p.setString(3, Qty);
        p.setDate(4, new java.sql.Date(Tanggal.getTime()));
        p.setString(5, Diskon);
        p.setString(6, Total);
        p.executeUpdate();
        p.close();

        JOptionPane.showMessageDialog(this, "Sukses Tambah Data Penjualan");

        // Refresh tabel
        try {
            Statement s = c.createStatement();
            String sqlRefresh = "SELECT NoPenjualan, KodeSp, Qty, Tanggal, Diskon, Total FROM tbldatapenjualan";
            ResultSet r = s.executeQuery(sqlRefresh);
            tampilDataDenganHeaderCustom(); // ganti ke method tampilDataPenjualan kalau kamu pakai
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    cekStmt.close();
    rs.close();

} catch (SQLException e) {
    System.out.println("Kesalahan SQL: " + e);
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCariDataCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCariDataCaretUpdate
try {
    Connection c = ClassDatabase.getKoneksi();
    Statement s = c.createStatement();
    String keyword = txtCariData.getText().trim();

    String sql = "SELECT NoPenjualan, KodeSp, Qty, Tanggal, Diskon, Total " +
                 "FROM tbldatapenjualan " +
                 "WHERE NoPenjualan LIKE '%" + keyword + "%' OR " +
                 "KodeSp LIKE '%" + keyword + "%' OR " +
                 "Qty LIKE '%" + keyword + "%' OR " +
                 "Tanggal LIKE '%" + keyword + "%' OR " +
                 "Diskon LIKE '%" + keyword + "%' OR " +
                 "Total LIKE '%" + keyword + "%'";

    ResultSet r = s.executeQuery(sql);
    tblPenjualan.setModel(DbUtils.resultSetToTableModel(r)); // Ini tabel penjualan

    // Atur ulang header kolom agar tetap rapi
    String[] namaKolom = {
        "No Penjualan",
        "Kode Sparepart",
        "Qty",
        "Tanggal",
        "Diskon",
        "Total"
    };
    for (int i = 0; i < namaKolom.length; i++) {
        tblPenjualan.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
    }
    tblPenjualan.getTableHeader().repaint();

    r.close();
    s.close();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data: " + e.getMessage());
}
    }//GEN-LAST:event_txtCariDataCaretUpdate

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtNoPenjualan.setText("");
        txtKodeSp.setText("");
        txtQty.setText("");
        txtCariData.setText("");
        tglPenjualan.setDate(null);
        txtTotal.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtKodeSpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeSpKeyReleased
tampilDataSparepart();
    }//GEN-LAST:event_txtKodeSpKeyReleased

    private void btnDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiskonActionPerformed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
hitungTotal();
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtDiskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiskonKeyReleased
hitungTotal();
    }//GEN-LAST:event_txtDiskonKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgMerah;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDiskon;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenjualan;
    private com.toedter.calendar.JDateChooser tglPenjualan;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKodeSp;
    private javax.swing.JTextField txtNamaSp;
    private javax.swing.JTextField txtNoPenjualan;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
