/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;

import service.ClassDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Kesya
 */
public class FormEntriDataBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEntriDataBarang
     */
    public FormEntriDataBarang() {
        initComponents();
        tampilData();
        tampilDataDenganHeaderCustom();
        
        txtTampilData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTampilDataCaretUpdate(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBgMerah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BGpinkKesaSp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodeSp = new javax.swing.JTextField();
        txtNamaSp = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        BgPinkTampilkan = new javax.swing.JPanel();
        btnTampilkanDataBarang = new javax.swing.JButton();
        txtTampilData = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataBarang = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(685, 600));

        PanelBgMerah.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM ENTRI DATA BARANG");

        BGpinkKesaSp.setBackground(new java.awt.Color(255, 204, 204));
        BGpinkKesaSp.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kesa Sparepart");

        javax.swing.GroupLayout BGpinkKesaSpLayout = new javax.swing.GroupLayout(BGpinkKesaSp);
        BGpinkKesaSp.setLayout(BGpinkKesaSpLayout);
        BGpinkKesaSpLayout.setHorizontalGroup(
            BGpinkKesaSpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGpinkKesaSpLayout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );
        BGpinkKesaSpLayout.setVerticalGroup(
            BGpinkKesaSpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGpinkKesaSpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Kode Sparepart");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nama Sparepart");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Harga Beli");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Harga Jual");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Stok");

        txtKodeSp.setPreferredSize(new java.awt.Dimension(71, 22));
        txtKodeSp.setScrollOffset(3);
        txtKodeSp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodeSpCaretUpdate(evt);
            }
        });
        txtKodeSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeSpActionPerformed(evt);
            }
        });

        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtKodeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaSp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKodeSp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNamaSp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtHargaBeli, txtHargaJual, txtKodeSp, txtNamaSp, txtStok});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnClose, btnDelete, btnEdit, btnSave});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addGap(20, 20, 20))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnClose, btnDelete, btnEdit, btnSave});

        BgPinkTampilkan.setBackground(new java.awt.Color(255, 204, 204));

        btnTampilkanDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampilkanDataBarang.setText("TAMPILKAN");
        btnTampilkanDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanDataBarangActionPerformed(evt);
            }
        });

        txtTampilData.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTampilDataCaretUpdate(evt);
            }
        });
        txtTampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTampilDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BgPinkTampilkanLayout = new javax.swing.GroupLayout(BgPinkTampilkan);
        BgPinkTampilkan.setLayout(BgPinkTampilkanLayout);
        BgPinkTampilkanLayout.setHorizontalGroup(
            BgPinkTampilkanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPinkTampilkanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTampilkanDataBarang)
                .addGap(37, 37, 37)
                .addComponent(txtTampilData, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        BgPinkTampilkanLayout.setVerticalGroup(
            BgPinkTampilkanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPinkTampilkanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BgPinkTampilkanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTampilkanDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTampilData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Sparepart", "Nama Sparepart", "Harga Beli", "Harga Jual", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblDataBarang);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout PanelBgMerahLayout = new javax.swing.GroupLayout(PanelBgMerah);
        PanelBgMerah.setLayout(PanelBgMerahLayout);
        PanelBgMerahLayout.setHorizontalGroup(
            PanelBgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBgMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BGpinkKesaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBgMerahLayout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BgPinkTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelBgMerahLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BGpinkKesaSp, BgPinkTampilkan});

        PanelBgMerahLayout.setVerticalGroup(
            PanelBgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBgMerahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGpinkKesaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBgMerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BgPinkTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        PanelBgMerahLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBgMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBgMerah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void tampilData() {
        try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok FROM tbldatabarang";
                ResultSet r=s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}
    
    public void tampilDataDenganHeaderCustom() {
    try {
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok FROM tbldatabarang";
        ResultSet r = s.executeQuery(sql);

        // Pakai DbUtils untuk isi datanya
        tblDataBarang.setModel(DbUtils.resultSetToTableModel(r));

        // Ganti nama header langsung
        String[] namaKolom = {
            "Kode Sparepart",
            "Nama Sparepart",
            "Harga Beli",
            "Harga Jual",
            "Stok"
        };

        for (int i = 0; i < namaKolom.length; i++) {
            tblDataBarang.getColumnModel().getColumn(i).setHeaderValue(namaKolom[i]);
        }

        tblDataBarang.getTableHeader().repaint();
        r.close();
        s.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    private void txtKodeSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeSpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeSpActionPerformed

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtKodeSp.setText("");
        txtNamaSp.setText("");
        txtHargaBeli.setText("");
        txtHargaJual.setText("");
        txtStok.setText("");
        txtKodeSp.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//Delete
            String KodeSp = this.txtKodeSp.getText();
            try {
                Connection c = ClassDatabase.getKoneksi();
                String sql = "DELETE FROM tbldatabarang WHERE KodeSp = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, KodeSp);
                
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Sukses Hapus Data");   
            }catch(SQLException e) {
                System.out.println(e);
            }finally{
            }
            try {
                Connection c = ClassDatabase.getKoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok FROM tbldatabarang";
                ResultSet r = s.executeQuery(sql);
                tampilDataDenganHeaderCustom();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// SAVE
String KodeSp = this.txtKodeSp.getText();
String NamaSp = this.txtNamaSp.getText();
String HargaBeli = this.txtHargaBeli.getText();
String HargaJual = this.txtHargaJual.getText();
String Stok = this.txtStok.getText();

// Validasi satu-satu
if(KodeSp.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Kode Sparepart Tidak Boleh Kosong");
    } else if (NamaSp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Sparepart Tidak Boleh Kosong");
        } else if (HargaBeli.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Harga Beli Tidak Boleh Kosong");
            } else if (HargaJual.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Harga Jual Tidak Boleh Kosong");
                } else if (Stok.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Stok Tidak Boleh Kosong");
                    } else {
                        try {
                            Connection c = ClassDatabase.getKoneksi();
                            String sql = "INSERT INTO tbldatabarang (KodeSp, NamaSp, HargaBeli, HargaJual, Stok) VALUES (?, ?, ?, ?, ?)";
                            PreparedStatement p = c.prepareStatement(sql);
                            p.setString(1, KodeSp);
                            p.setString(2, NamaSp);
                            p.setInt(3, Integer.parseInt(HargaBeli));
                            p.setInt(4, Integer.parseInt(HargaJual));
                            p.setInt(5, Integer.parseInt(Stok));
                            p.executeUpdate();
                            p.close();
                            JOptionPane.showMessageDialog(this, "Sukses Tambah Data");
                        } catch(SQLException e){
                            System.out.println("Kesalahan SQL: " + e);
                        }

                        // Refresh tabel
                        try {
                            Connection c = ClassDatabase.getKoneksi();
                            Statement s = c.createStatement();
                            String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok FROM tbldatabarang";
                            ResultSet r = s.executeQuery(sql);
                            tampilDataDenganHeaderCustom();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, e);
                        }
                }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtTampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTampilDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTampilDataActionPerformed

    private void txtTampilDataCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTampilDataCaretUpdate
        String keyword = txtTampilData.getText();
        try {
            Connection c = ClassDatabase.getKoneksi();
            String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok " +
                         "FROM tbldatabarang  " +
                         "WHERE KodeSp     LIKE ? " +
                         "   OR NamaSp     LIKE ? " +
                         "   OR HargaBeli  LIKE ? " +
                         "   OR HargaJual  LIKE ? " +
                         "   OR Stok       LIKE ? ";
            PreparedStatement p = c.prepareStatement(sql);
            String key = "%" + keyword + "%";
                for (int i = 1; i <= 5; i++) {
                    p.setString(i, key);
                }
            ResultSet r = p.executeQuery();
            
            tampilDataDenganHeaderCustom();
            r.close();
            p.close();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtTampilDataCaretUpdate

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnTampilkanDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanDataBarangActionPerformed
//Cari Data
    try {            
        Connection c = ClassDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM tbldatabarang WHERE KodeSp = '" + txtTampilData.getText() + "'";
        ResultSet r = s.executeQuery(sql);
        
        while (r.next()) {
            txtKodeSp.setText(r.getString("KodeSp"));
            txtNamaSp.setText(r.getString("NamaSp"));
            txtHargaBeli.setText(r.getString("HargaBeli"));
            txtHargaJual.setText(r.getString("HargaJual"));
            txtStok.setText(r.getString("Stok"));
        }

        r.close();
        s.close();
    } catch (SQLException e) {
        System.out.println("Terjadi kesalahan: " + e);
    }
    }//GEN-LAST:event_btnTampilkanDataBarangActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
//Update
String KodeSp = txtKodeSp.getText();
String NamaSp = txtNamaSp.getText();
String HargaBeli = txtHargaBeli.getText();
String HargaJual = txtHargaJual.getText();
String Stok = txtStok.getText();
if (KodeSp.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Kode Barang tidak boleh kosong!");
    } else if (NamaSp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Barang tidak boleh kosong!");
        } else if (HargaBeli.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harga Beli tidak boleh kosong!");
            } else if (HargaJual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga Jual tidak boleh kosong!");
                } else if (Stok.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Stok tidak boleh kosong!");
                    } else {
                            try{
                                    Connection c = ClassDatabase.getKoneksi();
                                    String sql = "UPDATE tbldatabarang SET NamaSp = ?, HargaBeli = ?, HargaJual = ?, Stok = ? WHERE KodeSp = ?";
                                    PreparedStatement p = c.prepareStatement(sql);
                                    p.setString(1, NamaSp);
                                    p.setInt(2, Integer.parseInt(HargaBeli));
                                    p.setInt(3, Integer.parseInt(HargaJual));
                                    p.setInt(4, Integer.parseInt(Stok));
                                    p.setString(5, KodeSp);
                                    p.executeUpdate();
                                    p.close();
                                    JOptionPane.showMessageDialog(this, "Sukses Update Data");       
                                        }catch(SQLException e){
                                            System.out.println(e);
                                        }finally{
                                      }} try {
                                               Connection c = ClassDatabase.getKoneksi();
                                                Statement s = c.createStatement();
                                                String sql = "SELECT KodeSp, NamaSp, HargaBeli, HargaJual, Stok FROM tbldatabarang";
                                                ResultSet r = s.executeQuery(sql);
                                                tampilDataDenganHeaderCustom();
                                       }catch (Exception e){
                                           JOptionPane.showMessageDialog(null, e);
                                       }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtKodeSpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodeSpCaretUpdate
        try {            
            Connection c = ClassDatabase.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbldatabarang WHERE KodeSp='" + this.txtKodeSp.getText() + "'";
            ResultSet r=s.executeQuery(sql);
           while (r.next()){
                this.txtNamaSp.setText(r.getString("NamaSp"));
                this.txtHargaBeli.setText(r.getString("HargaBeli"));
                this.txtHargaJual.setText(r.getString("HargaJual"));
                this.txtStok.setText(r.getString("Stok"));
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan" + e);
        }
    }//GEN-LAST:event_txtKodeSpCaretUpdate

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGpinkKesaSp;
    private javax.swing.JPanel BgPinkTampilkan;
    private javax.swing.JPanel PanelBgMerah;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTampilkanDataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDataBarang;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtKodeSp;
    private javax.swing.JTextField txtNamaSp;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTampilData;
    // End of variables declaration//GEN-END:variables
}
