/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import service.ClassDatabase;

/**
 *
 * @author Kesya
 */
public class MenuUtama extends javax.swing.JFrame {

    private FormEntriDataSupplier FormEntriDataSupplier;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        Connection c  = ClassDatabase.getKoneksi();
        this.setSize(770, 665);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DekstopMenuUtama = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuFormDataPelanggan = new javax.swing.JMenuItem();
        MenuFormDataBarang = new javax.swing.JMenuItem();
        MenuFormDataSupplier = new javax.swing.JMenuItem();
        MenuFormDataPembelianSparepart = new javax.swing.JMenuItem();
        MenuFormDataPenjualanSparepart = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CetakDataPelanggan = new javax.swing.JMenuItem();
        CetakDataBarang = new javax.swing.JMenuItem();
        CetakDataSupplier = new javax.swing.JMenuItem();
        CetakDataPembelian = new javax.swing.JMenuItem();
        CetakDataPenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DekstopMenuUtama.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(703, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        DekstopMenuUtama.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DekstopMenuUtamaLayout = new javax.swing.GroupLayout(DekstopMenuUtama);
        DekstopMenuUtama.setLayout(DekstopMenuUtamaLayout);
        DekstopMenuUtamaLayout.setHorizontalGroup(
            DekstopMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DekstopMenuUtamaLayout.setVerticalGroup(
            DekstopMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Master");

        MenuFormDataPelanggan.setText("Form Data Pelanggan");
        MenuFormDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormDataPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormDataPelanggan);

        MenuFormDataBarang.setText("Form Data Barang");
        MenuFormDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormDataBarangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormDataBarang);

        MenuFormDataSupplier.setText("Form Data Supplier");
        MenuFormDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormDataSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormDataSupplier);

        MenuFormDataPembelianSparepart.setText("Form Data Pembelian Sparepart");
        MenuFormDataPembelianSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormDataPembelianSparepartActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormDataPembelianSparepart);

        MenuFormDataPenjualanSparepart.setText("Form Data Penjualan Sparepart");
        MenuFormDataPenjualanSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormDataPenjualanSparepartActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormDataPenjualanSparepart);

        MenuBar.add(jMenu1);

        jMenu2.setText("Cetak");

        CetakDataPelanggan.setText("Data Pelanggan");
        CetakDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakDataPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(CetakDataPelanggan);

        CetakDataBarang.setText("Data Barang");
        CetakDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakDataBarangActionPerformed(evt);
            }
        });
        jMenu2.add(CetakDataBarang);

        CetakDataSupplier.setText("Data Supplier");
        CetakDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakDataSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(CetakDataSupplier);

        CetakDataPembelian.setText("Data Pembelian");
        CetakDataPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakDataPembelianActionPerformed(evt);
            }
        });
        jMenu2.add(CetakDataPembelian);

        CetakDataPenjualan.setText("Data Penjualan");
        CetakDataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakDataPenjualanActionPerformed(evt);
            }
        });
        jMenu2.add(CetakDataPenjualan);

        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DekstopMenuUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DekstopMenuUtama, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFormDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormDataPelangganActionPerformed
        FormDataPelanggan s = new FormDataPelanggan();
        this.DekstopMenuUtama.add(s);
        s.show();
    }//GEN-LAST:event_MenuFormDataPelangganActionPerformed

    private void MenuFormDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormDataBarangActionPerformed
        FormEntriDataBarang s = new FormEntriDataBarang();
        this.DekstopMenuUtama.add(s);
        s.show();
    }//GEN-LAST:event_MenuFormDataBarangActionPerformed

    private void MenuFormDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormDataSupplierActionPerformed
        FormEntriDataSupplier s = new FormEntriDataSupplier();
        this.DekstopMenuUtama.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_MenuFormDataSupplierActionPerformed

    private void MenuFormDataPembelianSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormDataPembelianSparepartActionPerformed
        FormDataPembelianSparepart s = new FormDataPembelianSparepart();
        this.DekstopMenuUtama.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_MenuFormDataPembelianSparepartActionPerformed

    private void MenuFormDataPenjualanSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormDataPenjualanSparepartActionPerformed
        FormDataPenjualanSparepart s = new FormDataPenjualanSparepart();
        this.DekstopMenuUtama.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_MenuFormDataPenjualanSparepartActionPerformed

    private void CetakDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakDataPelangganActionPerformed
try {
        InputStream reportPath = getClass().getResourceAsStream("/form/LaporanDataPelanggan.jasper");

        if (reportPath == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("logo", getClass().getResourceAsStream("/form/hhh.png"));
        Connection conn = ClassDatabase.getKoneksi();

        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal membuka laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_CetakDataPelangganActionPerformed

    private void CetakDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakDataSupplierActionPerformed
try {
        InputStream reportPath = getClass().getResourceAsStream("/form/LaporanDataSupplier.jasper");

        if (reportPath == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("logo", getClass().getResourceAsStream("/form/hhh.png"));
        Connection conn = ClassDatabase.getKoneksi();

        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal membuka laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_CetakDataSupplierActionPerformed

    private void CetakDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakDataBarangActionPerformed
try {
        InputStream reportPath = getClass().getResourceAsStream("/form/LaporanDataBarang.jasper");

        if (reportPath == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("logo", getClass().getResourceAsStream("/form/hhh.png"));
        Connection conn = ClassDatabase.getKoneksi();

        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal membuka laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_CetakDataBarangActionPerformed

    private void CetakDataPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakDataPembelianActionPerformed
try {
        InputStream reportPath = getClass().getResourceAsStream("/form/LaporanDataPembelian.jasper");

        if (reportPath == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("logo", getClass().getResourceAsStream("/form/hhh.png"));
        Connection conn = ClassDatabase.getKoneksi();

        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal membuka laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_CetakDataPembelianActionPerformed

    private void CetakDataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakDataPenjualanActionPerformed
try {
        InputStream reportPath = getClass().getResourceAsStream("/form/LaporanDataPenjualan.jasper");

        if (reportPath == null) {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan!");
            return;
        }

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("logo", getClass().getResourceAsStream("/form/hhh.png"));
        Connection conn = ClassDatabase.getKoneksi();

        JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal membuka laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_CetakDataPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CetakDataBarang;
    private javax.swing.JMenuItem CetakDataPelanggan;
    private javax.swing.JMenuItem CetakDataPembelian;
    private javax.swing.JMenuItem CetakDataPenjualan;
    private javax.swing.JMenuItem CetakDataSupplier;
    private javax.swing.JDesktopPane DekstopMenuUtama;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuFormDataBarang;
    private javax.swing.JMenuItem MenuFormDataPelanggan;
    private javax.swing.JMenuItem MenuFormDataPembelianSparepart;
    private javax.swing.JMenuItem MenuFormDataPenjualanSparepart;
    private javax.swing.JMenuItem MenuFormDataSupplier;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
